# Generated by Django 3.1.2 on 2020-10-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201008_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.CharField(blank=True, default='auctions/images/default_image.jpg', max_length=200),
        ),
    ]
