# Generated by Django 3.1.2 on 2020-10-08 07:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20201008_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 8, 7, 39, 46, 797079, tzinfo=utc), verbose_name='created'),
        ),
    ]
