# Generated by Django 3.1.2 on 2020-10-08 08:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 8, 8, 19, 34, 862721, tzinfo=utc), verbose_name='created'),
        ),
    ]
