# Generated by Django 3.1.2 on 2020-10-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20201017_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='value',
            field=models.IntegerField(verbose_name='your bid'),
        ),
    ]
